text = section (barline section?)* EOF
barline = r'\ *\|\ *'
section = (
    ipsum
    / incipit
    / tilda
    / words)
    
words = (
    (word / missing_pitches) 
    (space? (word / missing_pitches))*
)
space = r'[\ \n]+'
word = r'[a-zA-Z\.\,\'\-]+'
missing_pitches = ('{' r'[^\}]+' '}') / '#'

incipit = word (space word)* '*'
// Can be psalm incipit or text that does not align to pitches
tilda = r'\~[a-zA-Z\.\,\'\-\ ]+'
ipsum = r'\~Ipsum [^\|]+'
